[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "metacal"
version = "0.1.0"
description = "Metacalibration weak lensing shear calibration"
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Erin Scott Sheldon" }]
license = "MIT"
license-files = ["LICENSE-MIT"]
dependencies = ["numpy", "galsim"]

[project.optional-dependencies]
test = ["pytest"]
gpu = ["cupy"]

[tool.setuptools.packages.find]
include = ["metacal*"]

[tool.setuptools.package-data]
"metacal.gpu" = ["cuda/*.cu", "cuda/*.cuh"]
